/**
 * 補充工程實績資料
 * 從部落格提取的額外案例
 */

import { Project } from './projects';

export const additionalProjects: Project[] = [
  {
    id: "taichung-dali-residential-2025",
    title: "台中市大里區大型造鎮案",
    location: "412台灣臺中市大里區健民路3號",
    city: "台中",
    district: "大里區",
    year: 2025,
    images: ["/images/hero-mat-1.jpg", "/images/hero-mat-2.jpg"],
    description: "台中市大里區大型造鎮案，鄰近健民路生活圈。住宅大廈入口採用止滑膠條地墊，提供安全舒適的進出體驗。",
    youtubeVideoIds: ["gH4iJ5kL6mN"],
    tags: {
      buildingType: ["住宅大廈"],
      floorMaterial: ["磁磚"],
      installationType: ["表面式"],
      framingType: ["AL-620"],
      surfaceMaterial: ["止滑膠條"],
      drainageType: ["導水溝"],
      designFeature: ["大門外側"],
      location: ["入口"],
    },
    specs: {
      area: "25平方公尺",
      depth: "3cm",
      width: "200cm",
      length: "800cm",
    },
  },
  {
    id: "nantou-jade-mountain-2025",
    title: "玉山塔塔加遊客中心",
    location: "556台灣南投縣信義鄉太平巷118號",
    city: "南投",
    district: "信義鄉",
    year: 2025,
    images: ["/images/hero-mat-1.jpg"],
    description: "玉山塔塔加遊客中心地墊更新案例，採用止滑膠條與舊毯換新服務，提升遊客安全與視覺質感。",
    youtubeVideoIds: ["oP8qR9sT0uV"],
    tags: {
      buildingType: ["公共建築"],
      floorMaterial: ["地磚"],
      installationType: ["表面式"],
      framingType: ["無"],
      surfaceMaterial: ["止滑膠條"],
      drainageType: ["導水溝"],
      designFeature: ["舊毯換新"],
      location: ["遊客中心入口"],
    },
    specs: {
      area: "15平方公尺",
      depth: "2cm",
      width: "150cm",
      length: "600cm",
    },
  },
  {
    id: "taipei-beitou-qiyan",
    title: "北投奇岩重劃區",
    location: "112台灣台北市北投区三合街一段77號",
    city: "台北",
    district: "北投區",
    year: 2025,
    images: ["/images/hero-mat-2.jpg"],
    description: "北投奇岩重劃區高綠覆率、低密度開發住宅大廈。採用嵌入式刮泥墊搭配導水溝設計，提供防水與除泥功能。",
    tags: {
      buildingType: ["住宅大廈"],
      floorMaterial: ["地磚"],
      installationType: ["嵌入式"],
      framingType: ["AL-620"],
      surfaceMaterial: ["波羅紋毯面"],
      drainageType: ["導水溝"],
      designFeature: ["大門外側", "防水閘門"],
      location: ["主入口"],
    },
    specs: {
      area: "30平方公尺",
      depth: "3.5cm",
      width: "250cm",
      length: "900cm",
    },
  },
  {
    id: "taipei-nangang-factory",
    title: "台北南港廠辦",
    location: "115台灣台北市南港區南港路二段51號",
    city: "台北",
    district: "南港區",
    year: 2025,
    images: ["/images/hero-mat-1.jpg"],
    description: "台北南港廠辦風除室設計，採用荷蘭毯浪花紋黑色地墊，搭配退縮收邊框設計，提升專業形象。",
    tags: {
      buildingType: ["廠辦"],
      floorMaterial: ["地磚"],
      installationType: ["表面式"],
      framingType: ["AL-620"],
      surfaceMaterial: ["荷蘭毯VEBE浪花紋"],
      drainageType: ["導水溝"],
      designFeature: ["風除室-退縮收邊"],
      location: ["風除室"],
    },
    specs: {
      area: "20平方公尺",
      depth: "2.5cm",
      width: "180cm",
      length: "700cm",
    },
  },
  {
    id: "changhua-beidou-industrial",
    title: "北斗科學工業園區",
    location: "521台灣彰化縣北斗鎮新工二路66號",
    city: "彰化",
    district: "北斗鎮",
    year: 2025,
    images: ["/images/hero-mat-2.jpg"],
    description: "北斗科學工業園區廠辦入口採用梯形造型設計，使用荷蘭毯浪花紋黑色地墊，展現現代工業風格。",
    tags: {
      buildingType: ["廠辦"],
      floorMaterial: ["地磚"],
      installationType: ["表面式"],
      framingType: ["無"],
      surfaceMaterial: ["荷蘭毯VEBE浪花紋"],
      drainageType: ["導水溝"],
      designFeature: ["異形切割"],
      location: ["廠辦入口"],
    },
    specs: {
      area: "35平方公尺",
      depth: "2cm",
      width: "220cm",
      length: "950cm",
    },
  },
  {
    id: "taipei-zhongshan-office",
    title: "大直商辦",
    location: "10491台灣台北市中山區植福路289號",
    city: "台北",
    district: "中山區",
    year: 2025,
    images: ["/images/hero-mat-1.jpg"],
    description: "台北大直商辦採用荷蘭毯浪花紋灰色地墊，提供專業商務空間的視覺質感與功能性。",
    tags: {
      buildingType: ["廠辦"],
      floorMaterial: ["地磚"],
      installationType: ["表面式"],
      framingType: ["AL-620"],
      surfaceMaterial: ["荷蘭毯VEBE浪花紋"],
      drainageType: ["導水溝"],
      designFeature: ["大門外側"],
      location: ["商辦入口"],
    },
    specs: {
      area: "22平方公尺",
      depth: "2.5cm",
      width: "190cm",
      length: "750cm",
    },
  },
];
